#!/usr/bin/env bash
# configuring nginx with a custom http response header
apt-get update
apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;
     location /redirect_me {
        return 301 http://msn.com/;
     }
     error_page 404 /404.html;
     location /404 {
        root /var/www/html;
        internal;
     }
}
" > /etc/nginx/sites-available/default
sed -i '/server {/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo service nginx restart
