#!/usr/bin/env bash
# Install haproxy
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.7
apt-get install -y haproxy=2.7.\*

# Configure haproxy to send traffic to web-01 and web-02 using roundrobin algorithm
cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log global
    mode http
    option httplog
    option dontlognull
    retries 3
    option redispatch
    timeout connect 5000
    timeout client 10000
    timeout server 10000

frontend http-in
    bind *:80
    default_backend webservers

backend webservers
    balance roundrobin
    server web-01 34.227.101.223:80 check
    server web-02 54.162.236.122:80 check
EOF

# Make sure that haproxy can be managed via an init script
systemctl enable haproxy.service
service haproxy restart
